name: JSON Packages Generator
on:
  push:
    branches:
    - deauther
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Regenerate package'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Deauther Packager
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        wget https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json
        mkdir arm
        cp package_spacehuhn_index.json arm/package_deauther_index.json
        cp package_spacehuhn_index.json package_deauther_index.json
        
        # cat package_deauther_index.json
        # echo "Generated ARM package_deauther_index.json :"
        # cat arm/package_deauther_index.json
        git clone https://github.com/tobozo/Arduino.wiki.git
        cp -R arm Arduino.wiki/
        cp arm/package_deauther_index.json Arduino.wiki/
        cd Arduino.wiki/
        git remote rm origin
        git config --global user.email "tobozo@users.noreply.github.com"
        git config --global user.name "tobozo"
        git remote add origin https://tobozo:${{ secrets.GITHUB_TOKEN }}@github.com/tobozo/Arduino.wiki.git
        git add .
        git status
        git commit -m "JSON Packages autocommit"
        git push -u origin master
